version: '3.7'
services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports: 
      - 80:80
    volumes:
      - ./web/html:/usr/share/nginx/html

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3031:3031
    volumes:
      - ./app/src:/src